name: "YAML Reader converts to JSON"
description: "Reads a YAML File from Github Repo and return as json, if filemame starts with ci, it replaces some values 
in the string as well. Also can use for multiple files from multiple repos. Use case is to read configs for an 
environment from various repos. Configs are in files for each environment, so that parameter is global. "
author: "Surat Mukker"
inputs:
  gitRepo_Ref_Filepath:
    description: "Repository to read the file from, use none or omit if using gitRepos_Ref_Filepath"
    required: false
    default: "none"
  gitRepos_Ref_Filepath:
    description: "Repository to read the file from, use none or omit if using gitRepo_Ref_Filepath"
    required: false
    default: "none"
  filename:
    description: "File to read YAML from"
    required: true
  fileExt:
    description: "extension of the YAML file. Default is yaml"
    required: false
    default: ".yaml"
  ghaToken:
    description: "GH Access Token with read access to repo"
    required: true
outputs:
  yamlAsJson:
    description: "File contents as a JSON string"
    value: ${{ steps.fetch_yaml_as_json.outputs.yamlAsJson }}
runs:
  using: "composite"
  steps:
    - id: fetch_yaml_as_json
      run: |
        echo "::set-output name=yamlAsJson::$(echo $($GITHUB_ACTION_PATH/yaml_as_json.sh))"
      env:
        GITREPO_REF_FILEPATH: ${{inputs.gitRepo_Ref_Filepath}}
        GITREPOS_REF_FILEPATH: ${{inputs.gitRepos_Ref_Filepath}}
        FILENAME: ${{inputs.filename}}
        FILEEXT: ${{inputs.fileExt}}
        GHATOKEN: ${{inputs.ghaToken}}
      shell: bash
