name: Integration Test - Duplo Services Status
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Self test
        id: self-test
        uses: immersa-co/gha-ci-cd-utils/duplo-service-status@main
        with:
          host: "https://immersa-dev.duplocloud.net/"
          token: "${{ secrets.DUPLO_TOKEN_NONPROD }}"
          tenant: "dev01"
          tenant_id: "ed684c6c-9876-4fde-999a-849d6586a4a7"
          services: "['api', 'btcs', 'ftcs']"
