name: Integration Test - Slack Message
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Self test
        id: self-test
        uses: immersa-co/gha-ci-cd-utils/make-slack-post-wh@main
        with:
          slack_webhook_url: ${{ secrets.GHA_SLACK_SANDBOX }}
          action: "Testing github action in repo"
          action_success: "True"
          details: '{"Repo":"https://github.com/imsurat/gha-ci-cd-utils/", "Github Run" : "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"}'
